### ISSUE TITLE
Exchange mobility message  for user equipement

### ISSUE THREAD

**Issue by nbuffon** [Orange-OpenSource/its-client#132]
- [x] Road User (uuid, ..., CAM)
- [x] Road Hazard (uuid, cause, subcause, lifetime, ..., DENM)

GIVEN a producer using the SDK was connected to the message broker
AND a consumer using the SDK was connected to the message broker
AND the consumer subscribed to "default" root topic
WHEN a mobility message is sent by the producer on "default" root topic
THEN the consumer will receive it

**Comment by ymorin-orange** [comment]
In progress, ready for MR: https://github.com/ymorin-orange/its-client/tree/nyma/iot3-mobility

**Comment by ymorin-orange** [comment]
Besides the mandatory properties, I've arbitrarily decided on the minimalistic content a CAM and a DENM should carry, so that the abstraction is really high-level, or it would not abstract much...
