### ISSUE TITLE
Define mobility message contracts

### ISSUE THREAD

**Issue by tigroo** [Orange-OpenSource/its-client#137]
GIVEN I decided to create a new ITS message among CAM, DENM, CPM, information or status
WHEN I use the provided JSON schema file as specification to build the message
THEN I will be able to validate the format

- [X] ETSI ITS messages
  - [X] CAM
  - [X] CPM
  - [X] DENM
  - [X] SREM
  - [X] SSEM
- [X] Orange ITS messages 
  - [X] Information
  - [X] Status
    - [X] `cellular` and `gnss` are not required.
  - [X] neighbourhood
  - [X] region
- [ ] ~~remove the bad ls contract~~
- [X] validate the contracts into the GitHub workflow
- [X] standardize the header for all the messages (review cross the files)
   - [X] type -> message_type
   - [X] timestamp
   - [X] version
   - [X] source_uuid
   - [X] delete origin
   - [X] order fields: common first, specific last, in alphabetical order (please!)
- [X] align the version for the first packaging (2.0.0)
- [X] create a directory for each message type

**Comment by nbuffon** [comment]
`ls` script is actually used in the validation workflow to list all the schemas that has to be validated  
In the same workflow the `validate` script uses the output of `ls` one to validate each yielded script
