### ISSUE TITLE
Secure message exchanges for user equipment

### ISSUE THREAD

**Issue by tigroo** [Orange-OpenSource/its-client#138]
- [ ] Use certificate to secure connection to the broker
  - [x] MQTTS
  - [x] WSS

GIVEN the public root CA that signed the certificate of the message broker was provisioned
AND the message broker hostname's was discovered
AND the message broker was configured to only accept secure connections
WHEN I establish a connection using the certificate
THEN the connection will succeed
AND I will be able to subscribe and publish

**Comment by ymorin-orange** [comment]
In progress, ready for MR: https://github.com/ymorin-orange/its-client/tree/nyma/iot3-tls
