### ISSUE TITLE
pass all the parameter as configuration elements

### ISSUE THREAD

**Issue by tigroo** [Orange-OpenSource/its-client#14]

**Comment by nbuffon** [comment]
Do you mean as members of the Configuration struct ?  

Using a HashMap aims to avoid having to know about client specific parameters, each client implementing its own analyser might pass different parameters that are not relevant to other implementation  
I used the Configuration struct as a convenience solution as it is already provided through the pipeline to the analyser

**Comment by tigroo** [comment]
Oh, yes, I see : server parmaters versus Custom (payload layer) configuration. Yes, why not. To discuss, clarify and write alittle explanation intthe README at the end : I keep the issue opened, I add the documentation tag.

**Comment by nbuffon** [comment]
Sure this is open for discussion, I did it kind of the quick and easy way to be able to implement the setting override from a file in the jam detector  
As it could be useful short term but not mandatory I did not feel the need to mess up the whole Configuration struct and process

**Comment by nbuffon** [comment]
Merged in 2.0.0
Additional parameters that could be needed can easily be added via Configuration modification, ini file loading is ready
Closing issue
