### ISSUE TITLE
Fix source code headers (project name, licence, year,...)

### ISSUE THREAD

**Issue by tigroo** [Orange-OpenSource/its-client#160]
e.g.:

```
/*
 * Software Name : libits
 * SPDX-FileCopyrightText: Copyright (c) Orange SA
 * SPDX-License-Identifier: MIT
 *
 * This software is distributed under the MIT license,
 * see the "LICENSE.txt" file for more details or https://opensource.org/license/MIT/
 *
 * Authors: see CONTRIBUTORS.md
 * Software description: This Intelligent Transportation Systems (ITS) [MQTT](https://mqtt.org/) library based on the [JSon](https://www.json.org) [ETSI](https://www.etsi.org/committee/its) specification transcription provides a ready to connect project for the mobility (connected and autonomous vehicles, road side units, vulnerable road users,...).
 */
```

into telemtry.rs (not into libits) and a out of context Software description.

**Comment by nbuffon** [comment]
The header is valid against the Orange Open Source recommendations (https://infoportal-opensource.innov.intraorange/en/copyright-and-license-notices/)

I don't understand the `telemetry.rs` remark
The software name is actually mistaken, as it should match the built artifact's name, here `libits-client` as it is the name of the library pushed in crates.io
I'll fix it
