### ISSUE TITLE
Fix Unexpected input(s) 'log_output'

### ISSUE THREAD

**Issue by tigroo** [Orange-OpenSource/its-client#18]
An issue occurs on the docker action:

```
Warning: Unexpected input(s) 'log_output', valid inputs are ['entryPoint', 'args']
```

**Comment by PentW0lf** [comment]
can you show exact error that you got?

**Comment by tigroo** [comment]
Woops, it was fixed a long time ago, without close the issue. It was due to passing argument to the binary execution , replacing the docker templating action.
