### ISSUE TITLE
Rename type to message_type in schemas

### ISSUE THREAD

**Issue by nbuffon** [Orange-OpenSource/its-client#207]
All SDK have to align on using this new field name

**Comment by ymorin-orange** [comment]
* `type` -> `message_type`
* `origin` -> `delete`
* order of fields in schema for ease of comparison : fields common to all messages at the top, others below
* neighbourhood, region: add `source_uuid`, `timestamp`, and `validity_duration`
* status: `cellular` and `gnss` are not required.
* srem, ssem: move to sub-directories

**Comment by ymorin-orange** [comment]
Duplicate of #137
