### ISSUE TITLE
schemas: DSRC schema is in schemas' top-level directory

### ISSUE THREAD

**Issue by ymorin-orange** [Orange-OpenSource/its-client#234]
**What:**

* the DSRC schema is at the top-level of schemas' directory, `schema/dsrc_schema_1-0-0.json`;
* the references in schemas are now wrong: the DSRC is not in the same directory as the schemas.

---
**Expected:**

* the DSRC schema is in a sub-directory of its own, i.e. `schema/dsrc/dsrc_schema_1-0-0.json`;
* the references in schemas point to `../dsrc/dsrc_schema_1-0-0.json`.

**Comment by ymorin-orange** [comment]
@mathieu1fb Thanks for noticing the relative path for references.

**Comment by mathieu1fb** [comment]
I'm assigning it to myself: @Hugues360 I can take care of it if you do not mind!
