### ISSUE TITLE
python/its-status: collect all cellular KPIs

### ISSUE THREAD

**Issue by ymorin-orange** [Orange-OpenSource/its-client#74]
Currently, we only collect those KPIs associated with the current _access technology_,
with the assumption that there was a reciprocal relation between the two, i.e. that for
a given _access technology_ currently in use, only the corresponding signal KPIs would
be reported.

However, when connected on a 5G-NSA network, the _access technology_ is 4G (LTE), but
the modem is also connected on the 5G network, and thus the signal KPIs for that are
also available, and should be reported.

**Comment by ymorin-orange** [comment]
@tigroo @mathieu1fb FYI

**Comment by mathieu1fb** [comment]
Agreed. In that case, I will display "5G-NSA" when both 4G and 5G KPIs are collected, and "5G-SA" when only 5G KPIs are present.

**Comment by ymorin-orange** [comment]
> display "5G-NSA" when both 4G and 5G KPIs are collected, and "5G-SA" when only 5G KPIs are present.

That was the idea, indeed. Except there will be other corner cases.

For example, until now, when the _access-technology_ is one of HSDPA or HSUPA, we fake it to be UMTS (so `umts` is what gets reported as `cellular[].connection.technology`), and we report the UMTS signal KPIs.

From now on (i.e. after this issue is fixed), we'll report HSDPA and HSUPA as-is, without mangling (i.e. _hsdpa_ or _hsupa_ will get reported as `cellular[].connection.technology`), but there are no corresponding signal KPIs, but the UMTS ones. So, similar to LTE vs. 5G-NSA vs. 5G-SA, this is another corner case.

And there might be other imilar situations... Meh... :-(
